import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import SideBar from '@/components/SideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className='dark'
    >
      <body className={inter.className}>
        <Header />
        <div className='container mx-auto flex'>
          <SideBar />
          <div  className='w-full pt-6'>{children}</div>
        </div>
      </body>
    </html>
  );
}
